spring.application.name=data-processor
server.port=8082

app.kafka.topic.ingestion-events=ingestion.events.v1

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=data-processor-v1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.igaworks.dfinery.recruit.backend.model.ingestion
spring.kafka.consumer.properties.spring.json.value.default.type=com.igaworks.dfinery.recruit.backend.model.ingestion.DataIngestionRequestDTO
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# backpressure baseline: small poll batch + manual ack
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE
spring.kafka.listener.type=single
spring.kafka.listener.concurrency=1
spring.kafka.listener.poll-timeout=1500
spring.kafka.consumer.max-poll-records=50

processor.storage.base-dir=./processor-output
processor.storage.batch-size=2000
